pipeline {
    agent any
    stages {
        stage('Install ansible roles') {
            steps {
                 sh 'ansible-galaxy install --force  -r playbooks/requirements.yml --roles-path playbooks/roles; ansible-playbook playbooks/main.yml --tags "first-test" -vvv'
                //sh 'ansible-playbook main.yml --tags "first-test" -vvv'
            }
        }
    
    }
   
}
