pipeline {
    agent any
    stages {
        stage('Install ansible roles') {
            steps {
                 sh 'cd playbooks; pwd; ansible-galaxy install --force  -r ./requirements.yml --roles-path ./roles; ansible-playbook ./main.yml --tags "first-test" -vvv'
                //sh 'ansible-playbook main.yml --tags "first-test" -vvv'
            }
        }
    
    }
   
}
